name: mmdc-net
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pytorch-cuda=11.8
  - numpy
  - pillow
  - pyyaml
  - networkx
  - pandas
  - pip
  - pip:
    - opencv-python
    - scikit-image
    - matplotlib
    - scipy
    - tqdm
    - wandb
    - pytorch-msssim
    - albumentations
